name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Restore packages
      run: nuget restore C17-.Net-CustomerImport.sln

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Setup MSBuild.exe
      run: warrenbuckley/Setup-MSBuild@v1

    - name: Build Debug with MSBuild
      run: msbuild C17-.Net-CustomerImport.sln -p:Configuration=Debug

    - name: Build Release with MSBuild
      run: msbuild C17-.Net-CustomerImport.sln -p:Configuration=Release

    - name: Testing
      run: coverlet c17-.net-customerimport/bin/Debug/net452/CustomerImport.dll --target "dotnet" --targetargs "test c17-.net-customerimport/C17-.Net-CustomerImport.csproj --no-build --verbosity quiet" --format OpenCover --output customerimport.coverage.xml

    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)